DECLARE table_count NUMBER; 

BEGIN 
    SELECT COUNT(*) INTO table_count FROM user_tables WHERE table_name = 'BOARD';   

    IF table_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE board (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title VARCHAR2(200) NOT NULL,
                content CLOB NOT NULL,
                writer VARCHAR2(100) NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        ';
    END IF;
END; 
/

CREATE TABLE board (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(200) NOT NULL,
    content CLOB NOT NULL,
    writer VARCHAR2(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);