app.environment-name=\uAC1C\uBC1C

spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.thymeleaf.cache=true

server.error.include-message=never
server.error.include-stacktrace=never

logging.file.name=${APP_LOG_FILE:logs/spring-boot-study.log}
logging.charset.console=UTF-8
logging.charset.file=UTF-8

logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=14
logging.logback.rollingpolicy.total-size-cap=200MB

logging.level.root=INFO
logging.level.com.study.spring=INFO
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN
logging.pattern.level=%5p [requestId:%X{requestId:-}]