spring.application.name=spring

spring.application.name=spring-boot-study
spring.profiles.default=dev

spring.sql.init.mode=always
spring.sql.init.separator=/
spring.sql.init.continue-on-error=true

logging.level.com.study.spring.board=debug
logging.level.org.hibernate.orm.jdbc.bind=TRACE

app.firebase.enabled=${FIREBASE_ENABLED:true}
app.firebase.project-id=${FIREBASE_PROJECT_ID:}

spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true

spring.flyway.enabled=${FLYWAY_ENABLED:true}
spring.flyway.locations=classpath:db/migration/oracle
spring.flyway.clean-disabled=true
spring.flyway.baseline-on-migrate=false
spring.flyway.validate-on-migrate=true