-- 테이블 존재 여부를 수량으로 담을 숫자형(NUMBER) 변수 'table_count'를 선언합니다.
DECLARE table_count NUMBER; 

-- PL/SQL 실행 블록의 시작을 알립니다.
BEGIN 
    -- 현재 접속한 계정의 테이블 목록(user_tables)에서 테이블 이름이 'BOARD'인 개수를 조회하여 table_count 변수에 저장합니다.
    -- (※ 오라클 시스템 테이블의 테이블명은 대문자로 저장되므로 'BOARD'로 검색합니다.)
    SELECT COUNT(*) INTO table_count FROM user_tables WHERE table_name = 'BOARD';   

    -- 만약 'BOARD' 테이블 개수가 0개라면(즉, 테이블이 존재하지 않는다면) 조건문을 실행합니다.
    IF table_count = 0 THEN
        -- PL/SQL 내부에서 테이블 생성(DDL) 같은 동적 SQL 문장을 실행하기 위해 EXECUTE IMMEDIATE 구문을 사용합니다.
        EXECUTE IMMEDIATE '
            CREATE TABLE board (
                -- id: 기본키(PRIMARY KEY) 컬럼. 값 미지정 시 1씩 자동으로 증가하는 시퀀스 형태(IDENTITY)로 설정합니다.
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                -- title: 게시글 제목 컬럼. 최대 200바이트의 가변 길이를 가지며 필수 입력(NOT NULL)입니다.
                title VARCHAR2(200) NOT NULL,
                -- content: 게시글 내용 컬럼. 대용량 텍스트(CLOB) 형태를 저장하며 필수 입력(NOT NULL)입니다.
                content CLOB NOT NULL,
                -- writer: 작성자 이름/아이디 컬럼. 최대 100바이트의 가변 길이를 가지며 필수 입력(NOT NULL)입니다.
                writer VARCHAR2(100) NOT NULL,
                -- created_at: 작성일시 컬럼. 기본값으로 현재 날짜와 시간(CURRENT_TIMESTAMP)이 자동 입력됩니다.
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        ';
    -- IF 조건문을 종료합니다.
    END IF;
-- PL/SQL 실행 블록을 종료합니다.
END; 
-- 오라클 도구(SQL Developer, SQL*Plus 등)에서 위의 PL/SQL 블록을 실행하도록 명령하는 종료 구분 기호입니다.
/